### ISSUE TITLE
Adwaita icon theme is not latest

### ISSUE THREAD

**Issue by decipher3114** [polkaulfield/ubuntu-debullshit#6]
Ubuntu in their servers, serves Adwaita-icon-theme ver 41 or so. But the latest one is 43 which actually have those modern icons.

You need to fetch the packages from debain sid repo.
Here is the link: http://ftp.de.debian.org/debian/pool/main/a/adwaita-icon-theme/adwaita-icon-theme_43-1_all.deb

**Comment by polkaulfield** [comment]
That would be cool, I'll look into it. I want to make the script with separate options so one of these could be that

**Comment by polkaulfield** [comment]
Added your suggestion, looks sick :D
