### ISSUE TITLE
Respin RDX

### ISSUE THREAD

**Issue by rauldipeas** [polkaulfield/ubuntu-debullshit#8]
Hi, I want to share my work with You, I think that we have very similar goals, we're doing the same thing with a little different approaches.

I've taken some ideas from Your script and adapt into mine, so, I want to thank You for that.

https://rauldipeas.github.io/respin-rdx

Let me know Your thoughts about that.

**Comment by polkaulfield** [comment]
Np! Looks like a cool project :)
