### ISSUE TITLE
Log errors - most probably NOT relevant

### ISSUE THREAD

**Issue by mixpc** [polkaulfield/ubuntu-debullshit#9]
Hi,

Excellent utility! I read about it a blog and had to debullshit asap (option 1). I noticed a few little errors such as can't read, cannot remove, failed to remove that I thought you may be interested in. This is Ubuntu 23.04 running as Virtualbox VM. Actually, I don't think they may be relevant as my new vanilla GNOME Ubuntu runs smoothly.

```
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
[*] Removing terminal ads (if they are enabled)
sed: can't read /etc/default/motd-news: No such file or directory
[*] Deleting everything snap related
error: cannot remove "bare": snap "bare" is not removable: snap is being used by snap
       gtk-common-themes.
error: cannot remove "core22": snap "core22" is not removable: snap is being used by snaps firefox,
       gnome-42-2204, snap-store and snapd-desktop-integration.
firefox removed
gnome-42-2204 removed
gtk-common-themes removed
snap-store removed
error: cannot remove "snapd": snap "snapd" is not removable: remove all other snaps first
snapd-desktop-integration removed
bare removed
core22 removed
snapd removed
No snaps are installed yet. Try 'snap install hello-world'.
Warning: Stopping snapd.service, but it can still be activated by:
  snapd.socket

...

Purging configuration files for snapd (2.59.1+23.04ubuntu1) ...
rmdir: failed to remove '/etc/systemd/system/snapd.mounts.target.wants': No such file or directory
Discarding preserved snap namespaces
Final directory cleanup
Removing extra snap-confine apparmor rules
Removing snapd cache
Removing snapd state
Purging configuration files for firefox (1:1snap1-0ubuntu3) ...
Package: snapd
Pin: release a=*
Pin-Priority: -10
```

As said, excellent utility!

**Comment by polkaulfield** [comment]
Yeah, these errors are because snaps have dependencies between themselves. I ended up writing a function that keeps trying to uninstall them from the snap package list until none is left. The errors are from the attempts, as it says `is not removable: snap is being used...`. If the script passes it means that everything has been removed. Anyways i have to fix it and I'll probably catch the errors so users don't get worried about it
